services:
  escaner_red:
    container_name: LANGuard
    build: .
    ports:
      - "5555:5555"
    environment:
      TELEGRAM_BOT_TOKEN: "tu_bot_token"
      TELEGRAM_CHAT_ID: "tu_chat_id"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    cap_add:
      - NET_RAW
    restart: unless-stopped
