services:
  escaner_red:
    container_name: LANGuard
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: "tu_bot_token"
      TELEGRAM_CHAT_ID: "tu_chat_id"
      SECRET_KEY: "tu_llave_secreta"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data
    network_mode: "host"
    cap_add:
      - NET_RAW
    restart: unless-stopped
